services:
  app:
    container_name: surya
    build: .
    image: surya:latest
    volumes:
      - ./:/app/
      - ./recognition_model:/app/recognition_model
      - /mnt/data/nid_dataset_ocr:/app/data
      - ./experiment:/app/experiment
      - ./train.py:/app/train.py
      - ./converters.py:/app/converters.py
      - ./surya:/app/surya
      - ./test_data:/app/test_data
      - ./models:/app/models
      - ./test.py:/app/test.py
      - ./ocr_app.py:/app/ocr_app.py
      - ./entry.sh:/app/entry.sh
    ports: 
      - "8522:8501"
    command: ./entry.sh
    shm_size: 26G
    # command: bash
    # stdin_open: true
    runtime: nvidia
    environment:
      - OMP_NUM_THREADS=4
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


